version: '3.4'

services:
  notiondiscordbot:
    image: notiondiscordbot
    build:
      context: .
      dockerfile: ./Dockerfile
    volumes:
      - ./database:/Bot/database
    environment:
      - TOKEN=your-discord-bot-token
      - PREFIX=*
      - SECRET_KEY=MTAxMjQ3NzM1MjMwMDc3NzUxMg.GQ4iGf.X2RHjvr7pq22MJBurAodCKZTyuwWNRcenlnJTA
    restart: always
